#!/usr/bin/env zsh
#
# Outputs mame info for a given rom as json. More than one file is accepted.
#
# Usage: mameinfo --init-path <romdir>
#        mameinfo --info-file <romdir/rom1.zip> ...
#        mameinfo --exists <romdir/rom1.zip> ...
#        mameinfo [jq options] <romdir/rom1.zip> ...
# see oq --help
#
# requires standalone mame and oq. oq is a wrapper for jq with the ability to
# convert from xml. if jq is available, it will be used but oq is necessary for
# the conversion from xml to json. jq is faster when querying for results.
#
for r in mame oq; (( $+commands[$r] )) || missing+=($r)
if (( $+missing ))
then
  echo "${(j/, /)missing} required." >&2
  exit 1
fi

zparseopts -D -E - -init-path:=zinit_path -info-path=zinfo_path -exists=zexists || exit 1

# Write to name.json info files from mame xml output.
function mamexml_to_json_file {
  local line json_write=0 json_file
  while read -r line
  do
    if (( json_write ))
    then echo $line > $json_file
    else json_file=$init_path/.rominfo/info/$line.json
    fi
    json_write=$(( ! json_write ))
  done < <( oq -i xml -o json -cr '
    def arrayofobjects: if type == "object" then [.] else . end;
    def scrub: walk(if type == "object" then with_entries(
      select(.key != "#text" and .value != null) | .key |= ltrimstr("@")
    ) else . end );
    ( .mame."@build" | match("^[0-9.]+").string ) as $version |
    .mame.machine | arrayofobjects[] |
    ."@name",
    { version:$version,
      name:."@name",
      sourcefile:."@sourcefile",
      isbios:."@isbios",
      isdevice:."@isdevice",
      ismechanical:."@ismechanical",
      runnable:."@runnable",
      cloneof:."@cloneof",
      romof:."@romof",
      sampleof:."@sampleof",
      description:.description,
      year:.year,
      manufacturer:.manufacturer,
      biosset:.biosset | arrayofobjects,
      rom:.rom | arrayofobjects,
      disk:.disk | arrayofobjects,
      device_ref:.device_ref | arrayofobjects,
      sample:.sample | arrayofobjects,
      display:.display | arrayofobjects,
      sound:.sound,
      input:.input | {
        service:."@service",
        tilt:."@tilt",
        players:."@players",
        coins:."@coins",
        control:.control | arrayofobjects
      },
      driver:.driver,
      feature:.feature | arrayofobjects } | scrub' <<< $@ )
}

if (( #zinit_path ))
then
  init_path=${zinit_path[-1]:a}
  if [[ ! -d $init_path ]]
  then
    echo "init path does not exist." >&2
    exit 1
  fi
  # Remove decimals and truncate. MAME version 0.250.0.1 results in 0250.
  version=$( mame -version | awk -F'[ .]' '{print $1$2}' )
  if [[ -z $version ]]
  then version=unknown
  fi
  mkdir -p $init_path/.rominfo/$version
  ln -sF $version $init_path/.rominfo/info

  existing=( $init_path/.rominfo/info/*.json(N:t:r) )
  rom_names=( $init_path/*.(7z|zip)(N:t:r) )
  new_names=( ${rom_names:|existing} )

  if (( #new_names ))
  then
    # Some ROMs are not recognized by MAME due to its removal but the libretro
    # core still recognizes it. Use seperate xml files to process them.
    append_path=$HOME/Games/Support/RetroArch/database/mame-append
    append_names=( $append_path/*.xml(N:t:r) )
    new_append_names=( ${append_names:|existing} )
    for append in $new_append_names
    do mamexml_to_json_file $( < $append_path/$append.xml ) || exit 1
    done
    # Filter out what was already processed through appended xml files.
    if [[ -n ${new_names:|new_append_names} ]]
    then mamexml_to_json_file $( mame -listxml ${new_names:|new_append_names} ) || exit 1
    fi
  fi

  exit 0
fi

typeset -a jqargs
for arg in $@
do
  if [[ $arg:e == (7z|zip) ]]
  then
    # Use the first encountered rom path to locate `.rominfo/info`. Each rom is
    # replaced with a corresponding json file. This script will then cd into the
    # json directory to minimize the argument length being passed to jq. This
    # prevents the *argument list is too long* error when globbing a massive
    # collection of roms.
    if [[ -z $romdir ]]
    then
      romdir=$arg:a:h
      while [[ ! -s $romdir/.rominfo/info ]]
      do
        romdir=$romdir:h
        [[ $romdir == / ]] && {
          echo "rom path must be initialized with --init-path." >&2
          exit 1
        }
      done
      cd $romdir/.rominfo/info
    fi
    jqargs+=${arg:t:r}.json
  else
    jqargs+=$arg
  fi
done

if (( #zinfo_path ))
then
  print -l -- $jqargs:A
elif (( #zexists ))
then
  for json in $jqargs
  do [[ -f $json ]] || exit 1
  done
  exit 0
else
  if (( $+commands[jq] ))
  then jq $jqargs
  else oq $jqargs
  fi
fi
