#!/usr/bin/env zsh
#
# outputs mame info for a given rom as json.
#
# Usage: mameinfo [-d|--init-path] <rompath>
#        mameinfo [-x|--exists] <rompath/rom.zip>
#        mameinfo [jq options] [-g|--get,-l|--get-all] <rompath/rom.zip>
#        mameinfo [--info-file] <rompath/rom.zip>
# see oq --help
#
# requires standalone mame and oq. oq is a wrapper for jq with the ability to
# convert from xml. if jq is available, it will be used but oq is necessary for
# the conversion from xml to json. jq is faster when querying for results.
#
for r in mame oq; type $r &>/dev/null || missing+=($r)
if (( ${#missing} ))
then
  echo "${(j/, /)missing} required." >&2
  return 1
fi

zparseopts -D -E - {d,-init-path}:=zinit_path \
  {x,-exists,g,-get,l,-get-all,-info-path}:=zrom_file || return 1

if ! (( ${#zinit_path} + ${#zrom_file} ))
then
	cat <<-EOF >&2
	Usage: mameinfo [-d|--init-path] <rompath>
	       mameinfo [-x|--exists] <rompath/rom.zip>
	       mameinfo [jq options] [-g|--get,-l|--get-all] <rompath/rom.zip>
	       mameinfo [--info-file] <rompath/rom.zip>
	see oq --help
	EOF
  return 1
fi

if (( ${#zinit_path} ))
then
  init_path=${zinit_path[-1]}
  if [[ ! -d $init_path ]]
  then
    echo "init path does not exist." >&2
    return 1
  fi
  # Remove decimals and truncate. MAME version 0.250.0.1 results in 0250.
  version=$( mame -version | awk -F'[ .]' '{print $1$2}' )
  if [[ -z $version ]]
  then
    version=unknown
  fi
  mkdir -p $init_path/.rominfo/$version
  ln -sF $version $init_path/.rominfo/info
  return
fi

# absolute path required to prevent an endless loop.
rom_file=${zrom_file[-1]:a}
init_path=${rom_file:h}

if [[ ! -d $init_path ]]
then
  echo "missing directory: $init_path" >&2
  return 1
fi

# locate parent directory containing .rominfo.
while [[ ! -s $init_path/.rominfo/info ]]
do
  init_path=$init_path:h
  if [[ $init_path == / ]]
  then
    echo "rom path must be initialized." >&2
    return 1
  fi
done

flag=${zrom_file[1]}
name=${rom_file:t:r}
info_file=$init_path/.rominfo/info/$name.json

if [[ ! -s $info_file ]]
then
  append_path=~/Library/Application\ Support/RetroArch/database/${init_path:t}-append
  if ! mamexml=$( mame -listxml $name 2>/dev/null ) &&
  [[ -f $append_path/$name.xml ]]
  then
    mamexml=$( < $append_path/$name.xml )
  fi

  if [[ -n $mamexml ]]
  then
    echo $mamexml | oq -i xml -o json '
    def arrayofobjects: if type == "object" then [.] else . end;
    def scrub: walk(if type == "object" then with_entries(
      select(.key != "#text" and .value != null) | .key |= ltrimstr("@")
    ) else . end );
    { version: .mame."@build" | match("^[0-9.]+").string,
      machine:[ .mame.machine | arrayofobjects | .[] |
        { name: ."@name",
          description: .description,
          manufacturer: .manufacturer,
          year: .year,
          runnable: ."@runnable",
          isbios: ."@isbios",
          isdevice: ."@isdevice",
          ismechanical: ."@ismechanical",
          romof: ."@romof",
          cloneof: ."@cloneof",
          sampleof: ."@sampleof",
          sourcefile: ."@sourcefile",
          driver: .driver,
          feature: .feature | arrayofobjects,
          display: .display | arrayofobjects,
          sound: .sound,
          input: .input,
          disk: .disk | arrayofobjects,
          rom: .rom | arrayofobjects,
          sample: .sample | arrayofobjects,
          biosset: .biosset | arrayofobjects,
          device: .device | arrayofobjects,
          device_ref: .device_ref | arrayofobjects } | scrub ]}' > $info_file
  fi
fi

# if you don't want this message, use --exists.
if [[ $flag != (-x|--exists) && ! -f $info_file ]]
then
  echo "info missing for $rom_file:t" >&2
  return 1
fi

if type jq &>/dev/null
then
  jq=jq
else
  jq=oq
fi

case $flag in
  -x|--exists)
    return $( test -f $info_file )
    ;;
  -g|--get)
    $jq --arg name $info_file:t:r '.machine[]|select(.name == $name)' $info_file | $jq ${@:-.}
    ;;
  -l|--get-all)
    $jq ${@:-.} $info_file
    ;;
  --info-path)
    echo $( realpath $info_file )
    ;;
esac
