#!/usr/bin/env zsh

zparseopts -D -E - -appendconfig:=apcfg {L,-libretro}:=core

appendconfig=( $ZSH_SCRIPT:h:h/Resources/override.cfg $apcfg[-1] )

argv=(
  #ARCH#
  -b com.libretro.dist.RetroArch
  --args $@
  --appendconfig ${(j[|])appendconfig}
  --libretro ${core[-1]:-#CORE#}
  #GAME#
)
open $@
